spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User-Management-service
    username: beli1234
    password: beli1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL8Dialect
